source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'TestPod_Example' do
  pod 'TestPod', :path => '../'

  target 'TestPod_Tests' do
    inherit! :search_paths

    
  end
end
