name: Create Release

on:
  pull_request:
    types:
        - closed
    branches:
      - main
    paths:
      - 'CHANGELOG.md'
env:
  default_branch: main

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Branch
        run: |
          git fetch --all
          git pull -r
      - name: "Determine tag"
        run: |
          RELEASE_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo $RELEASE_TAG >> $GITHUB_ENV
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: $RELEASE_TAG

#       - name: "Create release"
#         uses: "actions/github-script@v6"
#         with:
#           github-token: "${{ secrets.GITHUB_TOKEN }}"
#           script: |
#             try {
#               const response = await github.rest.repos.createRelease({
#                 draft: false,
#                 generate_release_notes: true,
#                 name: process.env.RELEASE_TAG,
#                 owner: context.repo.owner,
#                 prerelease: false,
#                 repo: context.repo.repo,
#                 tag_name: process.env.RELEASE_TAG,
#               });

#               core.exportVariable('RELEASE_ID', response.data.id);
#               core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
#             } catch (error) {
#               core.setFailed(error.message);
#             }
